# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KUA4ztKvhM-MDR9c_LWkyRLDZZVT7M_S
"""

from flask import Flask, render_template, request
from search_vibes import search_tracks

app = Flask(__name__)

@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        user_vibe = request.form.get("vibe")
        style = request.form.get("style")
        results = search_tracks(user_vibe, style)

        if "track_id" in results.columns:
            results["spotify_link"] = "https://open.spotify.com/track/" + results["track_id"]

        return render_template("results.html", vibe=user_vibe, style=style, tracks=results.iterrows())

    return render_template("index.html")

if __name__ == "__main__":
    app.run(debug=True)