# -*- coding: utf-8 -*-
"""generate_embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138fdJl1sh62EsSWAnn1tTKRfWQOsWhUE
"""

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
import tqdm

# Load cleaned tracks
df = pd.read_csv("clean_tracks.csv")

# Load embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")  # small + fast

# Generate embeddings
print(" Encoding track text into vectors...")
embeddings = model.encode(
    df["text"].tolist(),
    show_progress_bar=True,
    convert_to_numpy=True
)

# Attach embeddings to dataframe
df["embedding"] = list(embeddings)

# Save as pickle
df.to_pickle("tracks_with_embeddings.pkl")

print(f"Saved {len(df)} tracks with embeddings to tracks_with_embeddings.pkl")

